<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework><OutputType>WinExe</OutputType>
    <PlatformTarget>x64</PlatformTarget><LangVersion>9.0</LangVersion><Nullable>enable</Nullable>
    <ApplicationManifest>../../src/ReactorV.Preloader/app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ReactorV.Runtime/RageWebUI.Runtime.csproj" />
    <Reference Include="System.Drawing" /><Reference Include="System.Windows.Forms" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
